title = "Repix Demo"
baseUrl = "http://bjp.li/"

theme = "repix"
themesDir = "../.."

languageCode = "en"
defaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 1

[Languages.ru]
weight = 2

[params]
#google_analytics_id = ""
twitter_username = "plindberg"
#paginate = 5
